### ISSUE TITLE
Better support for self signed certificates

### ISSUE THREAD

**Issue by jborean93** [chocolatey/c4b-ansible#7]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my request.

### Is Your Feature Request Related To A Problem? Please describe.

Using a self signed certificate has problems as a few steps expect Windows to trust the certificate for the server. While this is a great default it would be nice if there was an option to ignore certificate errors for tasks that are connecting to the Nexus endpoint.

For example this is the first task that fails when using a self signed certificate

```yaml
TASK [Set Nexus Password using Default Password] *************************************************************************************************************************************
task path: /home/jborean/dev/c4b-ansible/setup-nexus.yml:128
fatal: [ccm_server]: FAILED! =>
    changed: false
    elapsed: 0.1874127
    msg: 'Unhandled exception occurred when sending web request. Exception: The underlying
        connection was closed: Could not establish trust relationship for the SSL/TLS
        secure channel.'
    status_code: null
    url: https://server.chocolatey.test:8443/service/rest/v1/security/users/admin/change-password
```

### Describe The Solution. Why is it needed?

This is more for testing when someone cannot get an actual trusted certificate. By exposing an option to have tasks ignore the cert checks things can work just as if a signed certificate was used.

### Additional Context

N/A
